### ISSUE TITLE
Does not support ng-model

### ISSUE THREAD

**Issue by hyrumwhite** [klaascuvelier/angular-floating-label#1]
I'm trying out your code, currently the animation functionality disappears when you add an ng-model to the input tag.

**Comment by klaascuvelier** [comment]
Thanks for noticing, I'll check this asap.

**Comment by jtorbicki** [comment]
Quickfix, change this: 

<pre lang="javascript"><code>
templateAttributes.push(attr + '="' + $attrs[attr] + '"');
</code></pre>

to this:

<pre lang="javascript"><code>
if (attr !== 'floatingLabel') {
  templateAttributes.push($attrs.$attr[attr] + '="' + $attrs[attr] + '"');
}
</code></pre>

**Comment by klaascuvelier** [comment]
Thanks for the suggestion @jtorbicki! This worked perfectly.
I updated the code and the example (to have an ng-model to prove this fix).

If I find some time I will maybe add some automated tests and publish this to bower and npm

Thanks @jtorbicki and @hyrumwhite
