### ISSUE TITLE
What we do other field such as select fied except input field

### ISSUE THREAD

**Issue by AnsonShaji1** [klaascuvelier/angular-floating-label#11]
I am trouble in doing floating-label in select field in angular.Input field is fine.its working.But select field, textarea, ui-select, ui-multiselect and other field how to set floating label.Can you please share your suggestions.

**Comment by klaascuvelier** [comment]
Hi @AnsonShaji1 
As those elements do not have a placeholder attribute, it's not possible to support them.

There's no plans on making a workaround for these elements.

**Comment by AnsonShaji1** [comment]
Hai,
     Thank you for your value time spend my issue in code.


Regards,
Anson
