### ISSUE TITLE
Why is this module called "components"?

### ISSUE THREAD

**Issue by faridnsh** [klaascuvelier/angular-floating-label#4]

**Comment by klaascuvelier** [comment]
The idea was to have more ui components in here eventually.

**Comment by laurynas-karvelis** [comment]
+1, "components" seems too generic.

**Comment by ablamunits** [comment]
+1 
Is this going to be changed? A bit weird to have an open source project with such a name.

**Comment by klaascuvelier** [comment]
There's no plan to change it.
The reasoning is that it's a ui-component so it goes into a `components` module.

Don't think it's worth investing time in Angular 1 libraries to be honest.
