### ISSUE TITLE
not working for input type="number"?

### ISSUE THREAD

**Issue by kucheech** [klaascuvelier/angular-floating-label#8]
Hi,

it is working great for input types "text" and "email".
However, it does not seem to work for type "number".
Please advise, thanks in advance.

**Comment by kucheech** [comment]
I seen your fix but it is not in the dist/floating-label.js

**Comment by klaascuvelier** [comment]
@kucheech: https://github.com/klaascuvelier/angular-floating-label/commit/b88a29f4b18fbbfbcdadeb96a889b1589fb45d94
It looks like it is?
Am I missing something?

**Comment by kucheech** [comment]
what i meant is that your fix is only in the src but not in the dist

**Comment by klaascuvelier** [comment]
You are right, I fixed it now :)
